version: '3.8'


services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_config:/etc/clickhouse-server
      - ./clickhouse_log:/var/log/clickhouse-server
      - "./clickhouse_config/config.xml:/etc/clickhouse-server/config.xml"
      - "./clickhouse_config/users.xml:/etc/clickhouse-server/users.xml"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_HTTP_PORT=8123
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=changeme
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_ACCESS_MANAGEMENT=1
