version: '3.8'

x-airflow-common:
  &airflow-common
  build:
      context: .
      dockerfile: Dockerfile.webserver
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
  volumes:
    - ./dags:/opt/airflow/dags
    - ./airflow-data/logs:/opt/airflow/logs
    - ./airflow-data/plugins:/opt/airflow/plugins
    - ./airflow-data/airflow.cfg:/opt/airlfow/airflow.cfg
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5436:5432"
    volumes:
      - ./db/.database/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 2s
      retries: 10
    restart: always
  
  vertica:
    image: vertica/vertica-ce:latest
    environment:
      - VERTICA_DATABASE=vertica
      - VERTICA_USER=dbadmin
      - VERTICA_PASSWORD=mydbpassword
    ports:
      - "5433:5433"
    volumes:
      - ./vertica_data:/data
    restart: always

  migrate:
    image: arigaio/atlas:latest
    restart: on-failure
    command: >
      migrate apply 1
      --url "postgresql://airflow:airflow@postgres:5432/airflow?search_path=public&sslmode=disable"
      --allow-dirty

    depends_on:
    - postgres
    volumes:
    - ./db/migrations/:/migrations


  airflow-init:
    << : *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || ( airflow db init &&
        airflow users create
          --role Admin
          --username airflow
          --password airflow
          --email airflow@airflow.com
          --firstname airflow
          --lastname airflow )
    restart: on-failure

  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - 8080:8080
    container_name: airflow_webserver
    restart: always

  airflow-scheduler:
    << : *airflow-common
    command: airflow scheduler
    container_name: airflow_scheduler
    restart: always
  app:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PASSWORD=AIRFLOW
    profiles:
      - js




  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_config:/etc/clickhouse-server
      - ./clickhouse_log:/var/log/clickhouse-server
      - "./clickhouse_config/config.xml:/etc/clickhouse-server/config.xml"
      - "./clickhouse_config/users.xml:/etc/clickhouse-server/users.xml"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_HTTP_PORT=8123
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=changeme
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_ACCESS_MANAGEMENT=1
